const ui={
  cover:document.getElementById('cover'),ending:document.getElementById('ending'),chapter:document.getElementById('chapter'),score:document.getElementById('score'),task:document.getElementById('task'),dialog:document.getElementById('dialog'),speaker:document.getElementById('speaker'),text:document.getElementById('dialogText'),next:document.getElementById('nextBtn'),skip:document.getElementById('skipBtn'),start:document.getElementById('startBtn'),restart:document.getElementById('restartBtn'),endingText:document.getElementById('endingText'),game:document.getElementById('game')
};
const W=1280,H=720,canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');
canvas.width=W;canvas.height=H;canvas.style.width='100%';canvas.style.height='100%';canvas.style.display='block';ui.game.innerHTML='';ui.game.appendChild(canvas);
const chapters=[
{title:'第一章：雨城出发',place:'雨城',top:'#0f766e',bottom:'#082f49',target:3,itemName:'生态线索',items:[[260,420,'雨城水滴'],[540,310,'巡护脚印'],[860,230,'路线标记']],hazards:[[720,560,130,26,'噪声干扰']],lines:[['巡护员','欢迎来到雅安雨城。今天，你要带“小雨团”完成一次归山任务。'],['小雨团','我需要找到安全路线，也要避开会打扰栖息地的噪声。'],['巡护员','收集3个绿色生态线索，完成后继续前往森林巡护区。']]},
{title:'第二章：森林巡护',place:'森林',top:'#166534',bottom:'#052e16',target:4,itemName:'清理物',items:[[220,470,'塑料瓶'],[420,350,'旧包装'],[720,270,'干扰牌'],[990,400,'废纸团']],hazards:[[520,560,110,26,'施工噪声'],[900,560,120,26,'游客越线']],lines:[['巡护员','森林不是背景，它是动物真正的家。'],['小雨团','我会把干扰物带走，让路线恢复安静。'],['巡护员','收集4个清理物，生态值会提升。']]},
{title:'第三章：茶山同行',place:'茶山',top:'#84cc16',bottom:'#365314',target:4,itemName:'茶山知识',items:[[180,420,'蒙顶山茶'],[400,310,'生态茶园'],[680,230,'雨雾气候'],[980,350,'古道记忆']],hazards:[[330,560,120,26,'农残风险'],[790,560,120,26,'水土流失']],lines:[['茶山讲解员','雅安不只有熊猫，也有茶山、雨雾和古道记忆。'],['小雨团','原来生态保护和地方产业也可以联系在一起。'],['茶山讲解员','找到4个茶山知识点，前往最后的栖息地。']]},
{title:'第四章：熊猫归山',place:'栖息地',top:'#0f172a',bottom:'#14532d',target:5,itemName:'守护标记',items:[[160,450,'安静区'],[360,330,'水源地'],[620,240,'竹林带'],[860,340,'巡护点'],[1080,430,'归山路']],hazards:[[470,560,110,26,'强光干扰'],[760,560,130,26,'投喂风险'],[1030,560,120,26,'越界拍摄']],lines:[['巡护员','最后一段路，需要把所有守护标记点亮。'],['小雨团','好的文旅体验，不是打扰自然，而是理解自然。'],['巡护员','完成5个守护标记，让小雨团回到山里。']]}
];
const platforms=[[0,610,1280,90],[250,470,220,24],[540,380,220,24],[850,470,220,24]];
const keys={l:false,r:false,u:false};
const player={x:110,y:500,w:54,h:64,vx:0,vy:0,on:false,face:1};
const state={started:false,locked:true,chapter:0,score:0,got:0,line:0,items:[]};
function rr(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
function resetPlayer(){player.x=110;player.y=500;player.vx=0;player.vy=0;}
function sync(){const c=chapters[state.chapter];ui.chapter.textContent=c.title;ui.score.textContent=`生态值 ${state.score}`;ui.task.textContent=`任务 ${state.got} / ${c.target}`;}
function loadChapter(i){state.chapter=i;state.got=0;state.locked=true;state.items=chapters[i].items.map(v=>({x:v[0],y:v[1],label:v[2],got:false}));resetPlayer();sync();}
function showDialogue(lines){state.lines=lines;state.line=0;state.locked=true;showLine();}
function showLine(){const l=state.lines[state.line];if(!l){hideDialogue();return;}ui.speaker.textContent=l[0];ui.text.textContent=l[1];ui.dialog.style.display='block';ui.next.style.display='inline-block';ui.skip.style.display='inline-block';}
function nextLine(){state.line++;state.line>=state.lines.length?hideDialogue():showLine();}
function hideDialogue(){ui.dialog.style.display='none';ui.next.style.display='none';ui.skip.style.display='none';state.locked=false;}
function start(){ui.cover.style.display='none';state.started=true;showDialogue(chapters[state.chapter].lines);}
function restart(){ui.ending.style.display='none';state.score=0;loadChapter(0);state.started=true;showDialogue(chapters[0].lines);}
ui.start.onclick=start;ui.next.onclick=nextLine;ui.skip.onclick=hideDialogue;ui.restart.onclick=restart;
ui.start.addEventListener('touchstart',e=>{e.preventDefault();start();},{passive:false});
document.addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.l=true;if(['ArrowRight','d','D'].includes(e.key))keys.r=true;if(['ArrowUp','w','W',' '].includes(e.key)){keys.u=true;e.preventDefault();}});
document.addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.l=false;if(['ArrowRight','d','D'].includes(e.key))keys.r=false;if(['ArrowUp','w','W',' '].includes(e.key))keys.u=false;});
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function itemHit(it){const rx=player.x+player.w/2-it.x,ry=player.y+player.h/2-it.y;return rx*rx+ry*ry<45*45;}
function finish(){state.locked=true;const i=state.chapter,c=chapters[i];if(i<chapters.length-1){showDialogue([['系统提示',`${c.title}完成：${c.itemName}已收集，生态值提升。`],['巡护员','继续前进。真正的保护，是把每一次观看变成理解。']]);const t=setInterval(()=>{if(!state.locked){clearInterval(t);loadChapter(i+1);showDialogue(chapters[i+1].lines);}},180);}else{ui.endingText.textContent=`最终生态值：${state.score}。小雨团回到了更安静、更完整的栖息地。你完成了雨城路线识别、森林清理、茶山知识收集与栖息地守护任务。`;ui.ending.style.display='flex';}}
function update(){if(state.started&&!state.locked){player.vx=0;if(keys.l){player.vx=-5;player.face=-1;}if(keys.r){player.vx=5;player.face=1;}if(keys.u&&player.on){player.vy=-16;player.on=false;}}else player.vx=0;player.vy+=.75;player.x+=player.vx;player.y+=player.vy;player.x=Math.max(0,Math.min(W-player.w,player.x));player.on=false;for(const p of platforms){const r={x:p[0],y:p[1],w:p[2],h:p[3]};if(hit(player,r)&&player.vy>=0&&player.y+player.h-player.vy<=r.y+10){player.y=r.y-player.h;player.vy=0;player.on=true;}}if(player.y>H)resetPlayer();const c=chapters[state.chapter];for(const it of state.items){if(!it.got&&itemHit(it)){it.got=true;state.got++;state.score+=10;sync();if(state.got>=c.target)finish();}}if(!state.locked){for(const h of c.hazards){const r={x:h[0],y:h[1],w:h[2],h:h[3]};if(hit(player,r)){state.score=Math.max(0,state.score-1);sync();player.x-=18*player.face;}}}}
function bg(c){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,c.top);g.addColorStop(1,c.bottom);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(15,23,42,.18)';ctx.beginPath();ctx.moveTo(-50,520);ctx.lineTo(220,210);ctx.lineTo(520,520);ctx.fill();ctx.beginPath();ctx.moveTo(320,520);ctx.lineTo(610,170);ctx.lineTo(940,520);ctx.fill();ctx.beginPath();ctx.moveTo(760,520);ctx.lineTo(1050,220);ctx.lineTo(1360,520);ctx.fill();if(c.place==='雨城'){ctx.strokeStyle='rgba(191,219,254,.28)';for(let i=0;i<70;i++){let x=(i*83)%W,y=(i*47)%520;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-8,y+22);ctx.stroke();}}if(c.place==='茶山'){ctx.fillStyle='rgba(101,163,13,.6)';for(let i=0;i<7;i++){ctx.beginPath();ctx.ellipse(130+i*190,550-(i%2)*25,120,45,0,0,Math.PI*2);ctx.fill();}}if(c.place==='森林'||c.place==='栖息地'){ctx.fillStyle='rgba(74,222,128,.28)';for(let i=0;i<16;i++)ctx.fillRect(40+i*80,430+(i%3)*16,14,130);}ctx.fillStyle='rgba(47,35,22,.82)';rr(0,590,1280,90,34);ctx.fill();}
function panda(){const x=player.x+player.w/2,y=player.y+26;ctx.save();ctx.translate(x,y);ctx.scale(player.face,1);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,0,24,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(0,36,28,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111827';for(const [x,y,r] of [[-18,-12,10],[18,-12,10],[0,11,4]]){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}ctx.beginPath();ctx.ellipse(-9,2,8,11,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(9,2,8,11,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-9,1,2.5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(9,1,2.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111827';ctx.beginPath();ctx.ellipse(-22,36,8,20,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(22,36,8,20,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#86efac';rr(-12,50,24,10,5);ctx.fill();ctx.restore();}
function draw(){const c=chapters[state.chapter];bg(c);for(const p of platforms){ctx.fillStyle='#3f6212';rr(p[0],p[1],p[2],p[3],10);ctx.fill();ctx.fillStyle='#84cc16';rr(p[0],p[1],p[2],7,4);ctx.fill();}for(const h of c.hazards){ctx.fillStyle='#ef4444';rr(h[0],h[1],h[2],h[3],8);ctx.fill();ctx.fillStyle='#fee2e2';ctx.font='14px Microsoft YaHei';ctx.textAlign='center';ctx.fillText(h[4],h[0]+h[2]/2,h[1]-10);}for(const it of state.items){if(it.got)continue;ctx.fillStyle='#86efac';ctx.beginPath();ctx.arc(it.x,it.y,17,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.85)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(it.x,it.y,11,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#052e16';ctx.beginPath();ctx.moveTo(it.x,it.y-10);ctx.lineTo(it.x+10,it.y+10);ctx.lineTo(it.x-10,it.y+10);ctx.fill();ctx.fillStyle='#ecfccb';ctx.font='14px Microsoft YaHei';ctx.textAlign='center';ctx.fillText(it.label,it.x,it.y-28);}panda();}
function loop(){update();draw();requestAnimationFrame(loop);}loadChapter(0);loop();