const ui={cover:document.getElementById('cover'),ending:document.getElementById('ending'),chapter:document.getElementById('chapter'),score:document.getElementById('score'),task:document.getElementById('task'),dialog:document.getElementById('dialog'),speaker:document.getElementById('speaker'),text:document.getElementById('dialogText'),next:document.getElementById('nextBtn'),skip:document.getElementById('skipBtn'),start:document.getElementById('startBtn'),restart:document.getElementById('restartBtn'),endingText:document.getElementById('endingText'),game:document.getElementById('game'),tips:document.querySelector('.tips')};
const W=1280,H=720,canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=W;canvas.height=H;canvas.style.width='100%';canvas.style.height='100%';canvas.style.display='block';ui.game.innerHTML='';ui.game.appendChild(canvas);
const wrap=document.getElementById('wrap');
const panel=document.createElement('div');panel.style.cssText='position:absolute;left:50%;bottom:132px;transform:translateX(-50%);width:min(92%,980px);z-index:8;display:none;grid-template-columns:repeat(3,1fr);gap:10px';wrap.appendChild(panel);
const tools=document.createElement('div');tools.style.cssText='position:absolute;right:18px;top:112px;z-index:8;display:flex;gap:8px';wrap.appendChild(tools);
function toolBtn(t){const b=document.createElement('div');b.textContent=t;b.style.cssText='min-width:76px;padding:8px 12px;border-radius:999px;border:1px solid rgba(255,255,255,.18);background:rgba(15,23,42,.72);color:#fff;font-size:13px;font-weight:800;cursor:pointer;backdrop-filter:blur(12px);box-shadow:0 10px 28px rgba(0,0,0,.2);text-align:center';tools.appendChild(b);return b;}
const langBtn=toolBtn('EN'),soundBtn=toolBtn('声音 ON');
const TXT={zh:{eco:'生态值',task:'任务',op:'操作说明',tip:'← → / A D：移动<br>↑ / W / 空格：跳跃<br>选择行动策略，收集绿色生态记忆，避开红色干扰区。',next:'继续',skip:'跳过对话',sound:'声音',start:'开始归山',ending:'归山完成',restart:'重新体验',final:'小雨团回到了更安静、更完整的栖息地。你完成了雨城路线识别、森林清理、茶山知识收集与栖息地守护任务。'},en:{eco:'Eco',task:'Task',op:'Controls',tip:'← → / A D: Move<br>↑ / W / Space: Jump<br>Choose a strategy, collect green eco memories, avoid red disturbance zones.',next:'Next',skip:'Skip',sound:'Sound',start:'Start Journey',ending:'Homecoming Complete',restart:'Restart',final:'Rain Cub returns to a quieter and safer habitat. You completed route reading, forest cleanup, tea-mountain learning and habitat protection.'}};
const chapters=[
{t:{zh:'第一章：雨城出发',en:'Chapter 1: Rain City'},p:'rain',top:'#123e54',bot:'#0f766e',target:3,item:'生态线索',items:[[260,420,'雨城水滴','Rain Drop'],[540,310,'巡护脚印','Ranger Track'],[860,230,'路线标记','Safe Route']],haz:[[720,560,135,28,'噪声干扰','Noise']],lines:{zh:[['巡护员','雅安的雨不是背景，它会把山林里的声音放大。小雨团要回山，第一步是学会安静地经过。'],['小雨团','如果游客只想靠近拍照，山会不会变得很吵？'],['巡护员','所以这不是赶路游戏，而是一场“低打扰”的归山训练。']],en:[['Ranger','Rain in Ya’an is not just scenery. It amplifies every sound in the forest. The first lesson is to pass quietly.'],['Rain Cub','If tourists only chase photos, will the mountain become too loud?'],['Ranger','This is not a speed run. It is a low-disturbance homecoming.']]},choices:{zh:['静默观察：+8生态值','快速穿越：路径更短但扣2分','记录水声：解锁雨城记忆'],en:['Silent watching: +8 eco','Fast crossing: short but -2','Record rain sound: unlock memory']}},
{t:{zh:'第二章：森林巡护',en:'Chapter 2: Forest Patrol'},p:'forest',top:'#073b25',bot:'#14532d',target:4,item:'清理物',items:[[220,470,'塑料瓶','Bottle'],[420,350,'旧包装','Wrapper'],[720,270,'干扰牌','Warning Sign'],[990,400,'废纸团','Waste Paper']],haz:[[520,560,120,28,'施工噪声','Construction'],[900,560,125,28,'游客越线','Off-limit']],lines:{zh:[['巡护员','森林真正的边界，不是栏杆，而是人愿不愿意克制。'],['小雨团','我看到了一些不属于森林的东西。'],['巡护员','把它们带走。每一次清理，都是给动物留出一点安全感。']],en:[['Ranger','The true boundary of a forest is not a fence. It is human restraint.'],['Rain Cub','I see things that do not belong here.'],['Ranger','Take them away. Every cleanup gives wildlife a little more safety.']]},choices:{zh:['沿巡护线清理：+10生态值','拍照打卡：扣3分但获得传播线索','追踪脚印：道具更亮'],en:['Clean along patrol line: +10','Photo check-in: -3 but gain media clue','Track footprints: items glow']}},
{t:{zh:'第三章：茶山同行',en:'Chapter 3: Tea Mountain'},p:'tea',top:'#647b18',bot:'#365314',target:4,item:'茶山知识',items:[[180,420,'蒙顶山茶','Mengding Tea'],[400,310,'生态茶园','Eco Tea Field'],[680,230,'雨雾气候','Rain & Mist'],[980,350,'古道记忆','Ancient Road']],haz:[[330,560,120,28,'农残风险','Chemical Risk'],[790,560,120,28,'水土流失','Soil Loss']],lines:{zh:[['茶山讲解员','雅安的茶山连接着雨、路、村庄和人的生计。'],['小雨团','原来生态保护不是把人隔开，而是让人学会更好的相处。'],['茶山讲解员','收集茶山记忆，理解一片叶子怎样走过千年。']],en:[['Tea Guide','Ya’an tea mountains connect rain, roads, villages and livelihoods.'],['Rain Cub','Protection does not mean separating people. It means learning better coexistence.'],['Tea Guide','Collect tea memories and understand how one leaf travels through time.']]},choices:{zh:['听茶农讲述：+8生态值','走茶马古道支线：解锁文化记忆','只收集道具：无额外加成'],en:['Listen to tea farmers: +8','Take ancient road branch: culture memory','Collect only: no bonus']}},
{t:{zh:'第四章：熊猫归山',en:'Chapter 4: Homecoming'},p:'habitat',top:'#07111f',bot:'#14532d',target:5,item:'守护标记',items:[[160,450,'安静区','Quiet Zone'],[360,330,'水源地','Water Source'],[620,240,'竹林带','Bamboo Belt'],[860,340,'巡护点','Patrol Point'],[1080,430,'归山路','Home Route']],haz:[[470,560,110,28,'强光干扰','Strong Light'],[760,560,130,28,'投喂风险','Feeding Risk'],[1030,560,120,28,'越界拍摄','Cross-line Shot']],lines:{zh:[['巡护员','最后一段路，不再是收集，而是判断。'],['小雨团','我知道了，好的文旅体验不是打扰自然，而是理解自然。'],['巡护员','点亮守护标记，让归山成为一次真正的告别与守护。']],en:[['Ranger','The final path is no longer about collecting. It is about judgement.'],['Rain Cub','I understand. Good tourism does not disturb nature; it learns from nature.'],['Ranger','Light up the protection marks and make homecoming a real act of care.']]},choices:{zh:['保持距离：+12生态值','打开强光拍摄：扣8分','引导游客后退：+10生态值'],en:['Keep distance: +12','Use strong light: -8','Guide tourists back: +10']}}
];
const platforms=[[0,610,1280,90],[245,470,230,26],[530,382,230,26],[845,470,230,26]];
const keys={l:false,r:false,u:false};
const player={x:110,y:500,w:58,h:68,vx:0,vy:0,on:false,face:1};
const state={started:false,locked:true,choosing:false,chapter:0,score:0,got:0,line:0,items:[],particles:[],memories:[],lang:'zh',sound:true,time:0,audio:null};
function T(k){return TXT[state.lang][k]||k}function L(v){return Array.isArray(v)?v[state.lang==='zh'?0:1]:(v[state.lang]||v.zh||v)}
function rr(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
function initAudio(){if(state.audio||!state.sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;state.audio=new A()}
function sfx(type){if(!state.sound)return;initAudio();if(!state.audio)return;const a=state.audio,o=a.createOscillator(),g=a.createGain();o.type=type==='hit'?'square':type==='choice'?'triangle':'sine';o.frequency.value=type==='collect'?720:type==='hit'?120:type==='jump'?420:520;g.gain.value=.0001;o.connect(g);g.connect(a.destination);const now=a.currentTime;g.gain.exponentialRampToValueAtTime(type==='hit'?.05:.025,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+(type==='hit'?.18:.28));o.start(now);o.stop(now+.32)}
function resetPlayer(){player.x=110;player.y=500;player.vx=0;player.vy=0;player.on=false}
function sync(){const c=chapters[state.chapter];ui.chapter.textContent=L(c.t);ui.score.textContent=`${T('eco')} ${state.score}`;ui.task.textContent=`${T('task')} ${state.got} / ${c.target}`;ui.next.textContent=T('next');ui.skip.textContent=T('skip');ui.start.textContent=T('start');ui.restart.textContent=T('restart');if(ui.tips)ui.tips.innerHTML=`<strong>${T('op')}</strong><br>${T('tip')}`;langBtn.textContent=state.lang==='zh'?'EN':'中文';soundBtn.textContent=`${T('sound')} ${state.sound?'ON':'OFF'}`}
function loadChapter(i){state.chapter=i;state.got=0;state.locked=true;state.choosing=false;state.items=chapters[i].items.map(v=>({x:v[0],y:v[1],zh:v[2],en:v[3],got:false,pulse:Math.random()*6}));resetPlayer();sync()}
function showDialogue(lines){state.lines=lines;state.line=0;state.locked=true;panel.style.display='none';showLine()}
function showLine(){const l=state.lines[state.line];if(!l){showChoices();return}ui.speaker.textContent=L({zh:l[0],en:l[0]==='巡护员'?'Ranger':l[0]==='小雨团'?'Rain Cub':l[0]==='茶山讲解员'?'Tea Guide':l[0]});ui.text.textContent=l[1];ui.dialog.style.display='block';ui.next.style.display='inline-block';ui.skip.style.display='inline-block'}
function nextLine(){state.line++;state.line>=state.lines.length?showChoices():showLine()}function hideDialogue(){ui.dialog.style.display='none';ui.next.style.display='none';ui.skip.style.display='none';state.locked=false;panel.style.display='none';state.choosing=false}
function showChoices(){ui.dialog.style.display='none';ui.next.style.display='none';ui.skip.style.display='none';state.locked=true;state.choosing=true;const c=chapters[state.chapter];panel.innerHTML='';panel.style.display='grid';c.choices[state.lang].forEach((text,i)=>{const b=document.createElement('button');b.textContent=text;b.style.display='block';b.style.minHeight='64px';b.style.borderRadius='18px';b.style.padding='12px 14px';b.style.textAlign='left';b.style.color='#fff';b.style.background='rgba(15,23,42,.82)';b.style.border='1px solid rgba(255,255,255,.18)';b.style.boxShadow='0 12px 36px rgba(0,0,0,.25)';b.onclick=()=>choose(i);panel.appendChild(b)})}
function choose(i){const bonus=[[8,-2,5],[10,-3,4],[8,6,0],[12,-8,10]][state.chapter][i];state.score=Math.max(0,state.score+bonus);state.memories.push({chapter:state.chapter,choice:i});for(let k=0;k<18;k++)state.particles.push({x:player.x+30,y:player.y+20,vx:(Math.random()-.5)*5,vy:-Math.random()*4,life:50,c:bonus>=0?'#86efac':'#ef4444'});sfx('choice');sync();hideDialogue()}
function start(){initAudio();sfx('choice');ui.cover.style.display='none';state.started=true;showDialogue(chapters[state.chapter].lines[state.lang])}
function restart(){ui.ending.style.display='none';state.score=0;state.memories=[];loadChapter(0);state.started=true;showDialogue(chapters[0].lines[state.lang])}
ui.start.onclick=start;ui.next.onclick=nextLine;ui.skip.onclick=hideDialogue;ui.restart.onclick=restart;ui.start.addEventListener('touchstart',e=>{e.preventDefault();start()},{passive:false});langBtn.onclick=()=>{state.lang=state.lang==='zh'?'en':'zh';sync()};soundBtn.onclick=()=>{state.sound=!state.sound;if(state.sound)initAudio();sync()};
document.addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.l=true;if(['ArrowRight','d','D'].includes(e.key))keys.r=true;if(['ArrowUp','w','W',' '].includes(e.key)){keys.u=true;e.preventDefault()}});document.addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.l=false;if(['ArrowRight','d','D'].includes(e.key))keys.r=false;if(['ArrowUp','w','W',' '].includes(e.key))keys.u=false});
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}function itemHit(it){const rx=player.x+player.w/2-it.x,ry=player.y+player.h/2-it.y;return rx*rx+ry*ry<46*46}
function finish(){state.locked=true;const i=state.chapter,c=chapters[i];if(i<chapters.length-1){showDialogue(state.lang==='zh'?[['系统提示',`${L(c.t)}完成：${c.item}已收集，生态值提升。`],['巡护员','继续前进。真正的保护，是把每一次观看变成理解。']]:[['System',`${L(c.t)} complete. Eco memory collected.`],['Ranger','Move forward. Protection begins when viewing turns into understanding.']]);const t=setInterval(()=>{if(!state.locked&&!state.choosing){clearInterval(t);loadChapter(i+1);showDialogue(chapters[i+1].lines[state.lang])}},180)}else{ui.ending.querySelector('h2').textContent=T('ending');ui.endingText.textContent=`${state.lang==='zh'?'最终生态值':'Final Eco'}：${state.score}。${T('final')}`;ui.ending.style.display='flex';sfx('collect')}}
function update(){state.time+=1;if(state.started&&!state.locked){player.vx=0;if(keys.l){player.vx=-5.2;player.face=-1}if(keys.r){player.vx=5.2;player.face=1}if(keys.u&&player.on){player.vy=-16.5;player.on=false;sfx('jump')}}else player.vx=0;player.vy+=.72;player.x+=player.vx;player.y+=player.vy;player.x=Math.max(0,Math.min(W-player.w,player.x));player.on=false;for(const p of platforms){const r={x:p[0],y:p[1],w:p[2],h:p[3]};if(hit(player,r)&&player.vy>=0&&player.y+player.h-player.vy<=r.y+10){player.y=r.y-player.h;player.vy=0;player.on=true}}if(player.y>H)resetPlayer();const c=chapters[state.chapter];for(const it of state.items){if(!it.got&&itemHit(it)){it.got=true;state.got++;state.score+=10;sfx('collect');for(let k=0;k<24;k++)state.particles.push({x:it.x,y:it.y,vx:(Math.random()-.5)*6,vy:(Math.random()-.8)*6,life:50,c:'#86efac'});sync();if(state.got>=c.target)finish()}}if(!state.locked){for(const h of c.haz){const r={x:h[0],y:h[1],w:h[2],h:h[3]};if(hit(player,r)){state.score=Math.max(0,state.score-1);sync();player.x-=20*player.face;sfx('hit')}}}state.particles=state.particles.filter(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.life--;return p.life>0})}
function gradient(c){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,c.top);g.addColorStop(1,c.bot);ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}function ellipse(x,y,rx,ry,col){ctx.fillStyle=col;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function bg(c){gradient(c);const t=state.time;ctx.save();for(let i=0;i<3;i++){ctx.fillStyle=`rgba(255,255,255,${.04+i*.025})`;ctx.beginPath();ctx.ellipse(300+i*360+Math.sin(t*.006+i)*28,135+i*46,280,42,0,0,Math.PI*2);ctx.fill()}ctx.fillStyle='rgba(15,23,42,.18)';[[ -60,520,230,210,540,520],[300,530,620,160,960,530],[760,520,1060,210,1370,520]].forEach(m=>{ctx.beginPath();ctx.moveTo(m[0],m[1]);ctx.lineTo(m[2],m[3]);ctx.lineTo(m[4],m[5]);ctx.fill()});if(c.p==='rain'){ctx.strokeStyle='rgba(191,219,254,.34)';for(let i=0;i<90;i++){let x=(i*83+t*3)%W,y=(i*47+t*5)%520;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-10,y+26);ctx.stroke()}}if(c.p==='tea'){ctx.fillStyle='rgba(101,163,13,.55)';for(let i=0;i<9;i++)ellipse(70+i*160,548-(i%2)*22,120,42,'rgba(101,163,13,.55)');ctx.strokeStyle='rgba(236,252,203,.23)';for(let y=500;y<610;y+=18){ctx.beginPath();ctx.moveTo(0,y);ctx.quadraticCurveTo(640,y-55,1280,y);ctx.stroke()}}if(c.p==='forest'||c.p==='habitat'){for(let i=0;i<18;i++){ctx.fillStyle='rgba(74,222,128,.22)';ctx.fillRect(25+i*75,420+(i%3)*16,18,150);ctx.fillStyle='rgba(134,239,172,.16)';ctx.beginPath();ctx.ellipse(35+i*75,425+(i%3)*16,52,24,0,0,Math.PI*2);ctx.fill()}}ctx.fillStyle='rgba(47,35,22,.84)';rr(0,590,1280,92,34);ctx.fill();ctx.fillStyle='rgba(255,255,255,.05)';for(let i=0;i<30;i++)ellipse((i*97+t)%1280,620+Math.sin(i)*18,2,2,'rgba(255,255,255,.08)');ctx.restore()}
function platform(){platforms.forEach((p,i)=>{ctx.fillStyle='rgba(0,0,0,.22)';ellipse(p[0]+p[2]/2,p[1]+30,p[2]*.48,18,'rgba(0,0,0,.22)');const grd=ctx.createLinearGradient(0,p[1],0,p[1]+p[3]);grd.addColorStop(0,'#84cc16');grd.addColorStop(1,'#3f6212');ctx.fillStyle=grd;rr(p[0],p[1],p[2],p[3],12);ctx.fill();ctx.fillStyle='rgba(255,255,255,.15)';rr(p[0]+8,p[1]+4,p[2]-16,5,3);ctx.fill()})}
function panda(){const bob=Math.sin(state.time*.15)*2,x=player.x+player.w/2,y=player.y+26+bob;ellipse(x,player.y+player.h+8,34,9,'rgba(0,0,0,.26)');ctx.save();ctx.translate(x,y);ctx.scale(player.face,1);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,0,24,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(0,38,30,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111827';[[-18,-12,10],[18,-12,10],[0,12,4]].forEach(a=>{ctx.beginPath();ctx.arc(a[0],a[1],a[2],0,Math.PI*2);ctx.fill()});ctx.beginPath();ctx.ellipse(-9,2,8,11,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(9,2,8,11,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-9,1,2.6,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(9,1,2.6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0f172a';ctx.beginPath();ctx.ellipse(-22,38,8,21,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(22,38,8,21,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#86efac';rr(-15,50,30,10,5);ctx.fill();ctx.restore()}
function draw(){const c=chapters[state.chapter];bg(c);platform();ctx.font='14px Microsoft YaHei';ctx.textAlign='center';c.haz.forEach(h=>{ellipse(h[0]+h[2]/2,h[1]+18,h[2]*.5,10,'rgba(239,68,68,.22)');ctx.fillStyle='#ef4444';rr(h[0],h[1],h[2],h[3],10);ctx.fill();ctx.fillStyle='#fee2e2';ctx.fillText(state.lang==='zh'?h[4]:h[5],h[0]+h[2]/2,h[1]-10)});state.items.forEach(it=>{if(it.got)return;const pulse=1+Math.sin(state.time*.08+it.pulse)*.12;ellipse(it.x,it.y+24,28,8,'rgba(0,0,0,.22)');ctx.fillStyle='rgba(134,239,172,.16)';ctx.beginPath();ctx.arc(it.x,it.y,26*pulse,0,Math.PI*2);ctx.fill();ctx.fillStyle='#86efac';ctx.beginPath();ctx.arc(it.x,it.y,17*pulse,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.85)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(it.x,it.y,11*pulse,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#052e16';ctx.beginPath();ctx.moveTo(it.x,it.y-10);ctx.lineTo(it.x+10,it.y+10);ctx.lineTo(it.x-10,it.y+10);ctx.fill();ctx.fillStyle='#ecfccb';ctx.fillText(state.lang==='zh'?it.zh:it.en,it.x,it.y-30)});panda();state.particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/50);ellipse(p.x,p.y,3,3,p.c);ctx.globalAlpha=1});ctx.fillStyle='rgba(255,255,255,.72)';ctx.font='13px Microsoft YaHei';ctx.textAlign='left';ctx.fillText(`Memory ${state.memories.length}/4`,22,690)}
function loop(){update();draw();requestAnimationFrame(loop)}loadChapter(0);sync();loop();